// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: BaleCounter

#include "ui.h"

// Functions are defined in main.cpp with C linkage
void resetFlakeCount();
void resetBaleCount();
void resetBaleCountYear();

void handleResetFlakeCountBtnClick(lv_event_t * e)
{
	resetFlakeCount();
}

void handleResetBaleCountBtnClick(lv_event_t * e)
{
	resetBaleCount();
}

void handleResetBaleYearCountBtnClick(lv_event_t * e)
{
	resetBaleCountYear();
}
