// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: BaleCounter

#include "ui.h"

lv_obj_t * uiCYD_Main;
lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Button1 = NULL;
// event funtions

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Main);
    lv_img_set_src(ui_Image1, &ui_img_hay_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image1, -113);
    lv_obj_set_y(ui_Image1, 78);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Main);
    lv_img_set_src(ui_Image2, &ui_img_hay_flake_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 38
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_Image2, -114);
    lv_obj_set_y(ui_Image2, -89);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Main);
    lv_img_set_src(ui_Image3, &ui_img_balesperhour_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image3, -80);
    lv_obj_set_y(ui_Image3, -6);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Main);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -104);
    lv_obj_set_y(ui_Label1, 27);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Bales per hour");

    ui_Button1 = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 64);
    lv_obj_set_y(ui_Button1, -62);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);

    uiCYD_Main = ui_Main;

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    uiCYD_Main = NULL;
    ui_Main = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Label1 = NULL;
    ui_Button1 = NULL;

}
