// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: BaleCounter

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_FlakeContainer;
extern lv_obj_t * ui_FlakeCountImage;
extern lv_obj_t * ui_FlakeCountLabel;
extern lv_obj_t * ui_FlakeCountCurrent;
extern lv_obj_t * ui_FlakeCountPrev1;
extern lv_obj_t * ui_FlakeCountPrev2;
extern lv_obj_t * ui_FlakeSlash1;
extern lv_obj_t * ui_FlakeSlash2;
extern lv_obj_t * ui_BaleCountContainer;
extern lv_obj_t * ui_BaleCountImage;
extern lv_obj_t * ui_BaleCountLabel;
extern lv_obj_t * ui_BaleCount;
extern lv_obj_t * ui_BaleCountYearContainer;
extern lv_obj_t * ui_BaleCountImage1;
extern lv_obj_t * ui_BaleCountYearLabel;
extern lv_obj_t * ui_BaleCountYear;
extern lv_obj_t * ui_BaleCountHourContainer;
extern lv_obj_t * ui_FlakeCountImage1;
extern lv_obj_t * ui_FlakeCountNum1;
extern lv_obj_t * ui_BaleCountHour;
extern void ui_event_SettingsImgButton(lv_event_t * e);
extern lv_obj_t * ui_SettingsImgButton;
extern lv_obj_t * ui_SettingsPopupPanel;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_ResetCountsPage;
extern void ui_event_FlakeCountResetBtn(lv_event_t * e);
extern lv_obj_t * ui_FlakeCountResetBtn;
extern void ui_event_FlakeCountButtonText(lv_event_t * e);
extern lv_obj_t * ui_FlakeCountButtonText;
extern void ui_event_BaleCountResetBtn(lv_event_t * e);
extern lv_obj_t * ui_BaleCountResetBtn;
extern lv_obj_t * ui_BaleCountButtonText;
extern void ui_event_YearCountResetBtn(lv_event_t * e);
extern lv_obj_t * ui_YearCountResetBtn;
extern lv_obj_t * ui_YearCountButtonText;
extern lv_obj_t * ui_DateTimePage;
extern lv_obj_t * ui_SettingsTitleLabel;
extern void ui_event_CloseImgButton(lv_event_t * e);
extern lv_obj_t * ui_CloseImgButton;
// CUSTOM VARIABLES
extern lv_obj_t * uiCYD_Main;
extern lv_obj_t * uiCYD_FlakeContainer;
extern lv_obj_t * uiCYD_FlakeCountImage;
extern lv_obj_t * uiCYD_FlakeCount1;
extern lv_obj_t * uiCYD_FlakeCountCurrent;
extern lv_obj_t * uiCYD_FlakeCountPrev1;
extern lv_obj_t * uiCYD_FlakeCountPrev2;
extern lv_obj_t * uiCYD_BaleCountContainer;
extern lv_obj_t * uiCYD_BaleCountImage;
extern lv_obj_t * uiCYD_BaleCountLabel;
extern lv_obj_t * uiCYD_BaleCount;
extern lv_obj_t * uiCYD_BaleCountYearContainer;
extern lv_obj_t * uiCYD_BaleCountYear;
extern lv_obj_t * uiCYD_BaleCountHourContainer;
extern lv_obj_t * uiCYD_BaleCountHour;
extern lv_obj_t * uiCYD_SettingsImgButton;
extern lv_obj_t * uiCYD_SettingsPanel;
extern lv_obj_t * uiCYD_FlakeCountResetBtn;
extern lv_obj_t * uiCYD_FlakeCountButtonText;
extern lv_obj_t * uiCYD_BaleCountResetBtn;
extern lv_obj_t * uiCYD_BaleCountButtonText;
extern lv_obj_t * uiCYD_YearCountResetBtn;
extern lv_obj_t * uiCYD_YearCountButtonText;
extern lv_obj_t * uiCYD_SettingsTitleLabel;
extern lv_obj_t * uiCYD_CloseImgButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

